### ISSUE TITLE
Delete access token

### ISSUE THREAD

**Issue by poussy** [vimeo/vimeo.js#102]
Hello, 
I need some help to revoke, or delete an access token , and also need to know the exact duration after which an access token with scope 'public private upload' would be deleted if it s not used.

**Comment by tommypenner** [comment]
@poussy To delete a token, use the endpoint documented [here](https://developer.vimeo.com/api/reference/authentication-extras#delete_token). Here's the request expressed as a curl:

```
curl -X DELETE \
  https://api.vimeo.com/tokens \
  -H 'Accept: application/vnd.vimeo.*+json;version=3.4' \
  -H 'Authorization: bearer [token]'
```

Tokens are deleted after six months of inactivity.
