### ISSUE TITLE
getting video_files doesn't work, although the final scope indicates it should

### ISSUE THREAD

**Issue by brucemcpherson** [vimeo/vimeo.js#109]
I believe that there are now some complex rules around PRO versus basic accounts that can limit the data that can be returned by the api, but scopes are granted by the OAUTH process that (silently) cannot be fulfilled.

For example, a token request requiring video_files access is made by an app in a basic account, and access is consented to and authorized by a basic account user.

`https://api.vimeo.com/oauth/authorize?response_type=code&client_id=xxxxxxxxxxx&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fvimeo-redirect&scope=public%20private%20video_files&state=xxxxxxxxxx`

The user is presented with a consent screen that includes a request for access to his video files, and he consents.
![image](https://user-images.githubusercontent.com/1894020/58162173-8bcf0c80-7c79-11e9-8dbc-01bb5ce7f9f6.png)

The final scope returned confirms he has access to video_files
 `video_files private public`

And yet, when using the node vimeo client, no files property is returned (and no error is given) when accessing files in his own account.
This same (basic user) also has full access to a PRO user account also, yet queries to that account do not return files (or download) properties either.

What are the exact circumstances underwhich an app, which properly has consent to access video_files, can actually do so?

**Comment by tommypenner** [comment]
Users only have access to the video file links on their own account -- it is not possible to get the video file links for videos on another user's account. This also includes team members. Additionally, as you noted, video file access is only available to Vimeo PRO users and higher.

To get direct video file links, you'll need to authenticate as the video owner.

**Comment by brucemcpherson** [comment]
Ok - got it thank you. In summary the only way to get raw video file details is to 

- be a pro user
- use an access token you have consented to against your own account with the video_files scope. 
- Team members access tokens can never get other team members' files via the api, despite being able to see those files through the Vimeo UI.
