### ISSUE TITLE
How to fetch videos in a showcase?

### ISSUE THREAD

**Issue by onmyway133** [vimeo/vimeo.js#118]
Hi, thanks for the library. One thing that is unclear is the path documentation in make request https://www.npmjs.com/package/vimeo#make-requests

How does it work for showcase or collection?

**Comment by mandeldl** [comment]
Hey there!  You can check the API docs for information on these requests.
Showcases are still referred to by their previous name `albums` in the docs: https://developer.vimeo.com/api/reference/albums

There are also endpoints for Channels, Groups and Portfolios
