### ISSUE TITLE
Makes upload file accept node.js stream

### ISSUE THREAD

**Issue by b-hass** [vimeo/vimeo.js#139]
It would be nice if we could pass node streams directly to file upload instead of a file name. I guess it would be good in cases of long download streams. The AWS SDK for node accepts streams, for example.
Looking at the code it seems like it's already possible(?), but the README only mentions file paths as a possible argument to upload.

Thanks!

**Comment by pavlogavryliuk** [comment]
> It would be nice if we could pass node streams directly to file upload instead of a file name. I guess it would be good in cases of long download streams. The AWS SDK for node accepts streams, for example.
> Looking at the code it seems like it's already possible(?), but the README only mentions file paths as a possible argument to upload.
> 
> Thanks!

do you found a way to upload the file, without saving it to fs?

**Comment by karlhorky** [comment]
@b-hass I saw that you closed this as "completed" - has this feature been completed now?
