### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by rossng** [vimeo/vimeo.js#142]
I'm working on something that will integrate with the Vimeo API. 

It seems like this is the official JS SDK, but:

* It's missing support for most of the API surface area
* It doesn't use Promises
* It doesn't officially support TypeScript
* The last meaningful commits were two years ago
* The two key maintainers have left Vimeo

Is there any plan to revive this SDK?

**Comment by fweffort** [comment]
It seems so

**Comment by karlhorky** [comment]
It seems like @hedyyytang and @aaronm67 recently have been doing some documentation work.

@aaronm67 Is this a sign that this library will receive a bit more love? Last publish 4 years ago is not encouraging 😱

![Screen Shot 2022-07-18 at 15 17 39](https://user-images.githubusercontent.com/1935696/179519887-fba402be-ff37-4bef-aeb5-62a2451ed2a4.png)

Would be great to get:

- promises (#94)
- ability to get encoding / transcoding status of uploaded files (#89)
- updated dependencies / security vulnerabilities (#129)
- ESM / modern examples in documentation

---

An alternative looks like https://github.com/prshanilka/vimeo-api, but it has a very low download count, so could be even more unstable to depend on this.

**Comment by aaronm67** [comment]
This project is not abandoned, and part of the reason for moving documentation was to make it easier to keep it up to date with future feature requests.

> support of more API surface area

This is will not be done, the library supports the full API already. The library is intentionally designed as a thin wrapper with an upload wrapper, any API request can be made with `client.request(ROUTE)`, and unless new functionality is released where a wrapper is useful, the vast majority of APIs will only work using `client.request`.

> Promise Support
> ESM / modern examples in documentation

Async/promise spuport is the highest priority for this library, and updated documentation is a part of this.

> ability to get encoding / transcoding status of uploaded files (

This is an API feature that can be requested at Vimeo support, https://vimeo.com/help/contact, but we can't add a wrapper around an API that does not exist.

> updated dependencies / security vulnerabilities

We'll continue to address critical vulnerabilities, but vulnerabilities reported by `npm audit` are not a useful metric for this and will not be fixed.

**Comment by karlhorky** [comment]
Thanks for the update!

**Comment by karlhorky** [comment]
> but we can't add a wrapper around an API that does not exist

What would be cool is to add a convenience wrapper to the library around [your current recommendation of polling](https://github.com/vimeo/vimeo.js/issues/120#issuecomment-1189140178):

> Currently the only way to view when a video completes transcoding is by polling, i.e. `GET /videos/{video_id}?fields=status`

So a recursive async function that makes a `GET` request to this endpoint and then only resolves once an error occurs or the transcoding is done, eg. https://github.com/vimeo/vimeo.js/issues/120#issuecomment-1191415280
