### ISSUE TITLE
Upload videos from an SPA (Angular 12) - Which is the best approach?

### ISSUE THREAD

**Issue by mberiam** [vimeo/vimeo.js#149]
Hi! I am having a problem uploading a video from an Angular 12 application. I was trying to use the JS library provided by Vimeo, but it is not working due to a dependency on the fs.js lib, which Angular claims not to be able to run on the client side, only server side (with nodejs, for example). I would like support for uploading from an Angular application. Does Vimeo offer an API so I can connect to any endpoints and send the bytes and the file metadata?
Worth quoting I also tried to use that approach of making a POST with the metadata and the subsequent upload of the video, using the form provided as the return from the first POST, but Angular also doesn't support a form with an action for another page, as it's a single page application (SPA). Is there any documentation that teaches the dev team to integrate the SPA and Vimeo, after all this kind of application is really common nowadays. Thanks in advance

**Comment by aaronm67** [comment]
You can add any javascript handlers as desired to the form returned from POST /me/videos, it doesn't need to do a full reload.
