### ISSUE TITLE
adding thumbnail to video

### ISSUE THREAD

**Issue by majdkilou** [vimeo/vimeo.js#152]
hello, Im trying to make the requests that mentioned in uploading thumbnail https://developer.vimeo.com/api/upload/thumbnails#table-1
anyway I have a problem with getting the requests works in my backend repo, as I want to call the request from my frontend repo then.  

```

**Comment by majdkilou** [comment]
it seems  vimeo.js has no support! still waiting some advise on my issue, specially with getting the upload link step.

**Comment by aaronm67** [comment]
Please isolate your issue and ask a question about that, we can't debug your entire app.

**Comment by majdkilou** [comment]
yes my bad, I just want to ask which is the best way to do step  2 of Getting the upload link for the thumbnail. knowing that the "picture_uri" is : https://api.vimeo.com/videos/${videoCardId}/pictures

**Comment by aaronm67** [comment]
POST https://api.vimeo.com/videos/${videoCardId}/pictures

Will return a "link" field in the [response](https://developer.vimeo.com/api/reference/response/picture), this is the upload link for the thumbnail.

**Comment by majdkilou** [comment]
thanks for the advise, I did the post request but still getting status code 500 Internal Server Error, 

```
const ThumbnailUploadlink = (res, req) => {
  const { videoId } = req.body;
  const clientServerOptions11 = {
    uri: `https://api.vimeo.com/videos/${videoId}/pictures/`,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/vnd.vimeo.*+json;version=3.4',
      Authorization: getVimeoAuthorization(),
    },
  };
  request(clientServerOptions11, function (error, response) {
    if (error) {
      res.send(error);
    } else {
      res.send(response);
    }
  });
};
```

**Comment by aaronm67** [comment]
There is no trailing slash in the uri

**Comment by majdkilou** [comment]
removed the trailing slash, still getting same status code.

**Comment by aaronm67** [comment]
You can probably try hard coding your video ID and authorization, the URI is looks fine. I'm going to close this issue, please open a support ticket, https://vimeo.com/help/contact - this isn't a library issue, it's not able to be debugged without your specific account and request information.

**Comment by karlhorky** [comment]
Anyone who is coming here to try to create thumbnails from a frame of the video, you can check out my comment over here:

- [Add a new thumbnail at 0 seconds of a video](https://github.com/vimeo/vimeo.js/issues/186#issuecomment-1656793092)
