### ISSUE TITLE
Upload fails when video smaller than 0.5s

### ISSUE THREAD

**Issue by toannv1803** [vimeo/vimeo.js#156]
Hello,
I use SDK to upload videos. After that, I call API https://api.vimeo.com/videos/758598238 and receive an error
```
...
    "status": "uploading_error",
    "resource_key": "cbc9f225387a4dd526f2c48b90afc588710dd8b4",
    "upload": {
        "status": "error",
        "link": null,
        "upload_link": null,
        "complete_uri": null,
        "form": null,
        "approach": null,
        "size": null,
        "redirect_url": null
    },
    "transcode": {
        "status": "in_progress"
    },
...
```
In the other hand, I use chrome to upload (https://vimeo.com/upload/videos), and I receive an error "There was a problem with your upload."

Error happen when video < 0.5s

You can use those videos to reproduce: https://drive.google.com/drive/folders/1ZPGdB_rQYZwQ_7iTAGv9u5ZF9nRhazF3?usp=sharing
Version "vimeo": "^2.1.1"

Are there any solutions to fix it?

**Comment by justinruggles** [comment]
This is expected. Vimeo does not currently allow uploads that are less than 0.5s in duration.
