### ISSUE TITLE
Compilation Error 'Module not found: Error:'

### ISSUE THREAD

**Issue by edotappstore** [vimeo/vimeo.js#158]
Hi

I am getting the below compile time error when i try to use vimeo sdk,

**React version**: 18.1.0
**Vimeo SDK version** : 2.1.1

**Error :**

> Compiled with problems:X
> 
> ERROR in ./node_modules/vimeo/lib/vimeo.js 18:15-37
> 
> Module not found: Error: Can't resolve 'querystring' in 'E:\ClientApp\node_modules\vimeo\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
> 	- install 'querystring-es3'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "querystring": false }
> 
> 
> ERROR in ./node_modules/vimeo/lib/vimeo.js 19:16-30
> 
> Module not found: Error: Can't resolve 'url' in 'E:\ClientApp\node_modules\vimeo\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
> 	- install 'url'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "url": false }
> 
> 
> ERROR in ./node_modules/vimeo/lib/vimeo.js 20:17-32
> 
> Module not found: Error: Can't resolve 'http' in 'E:\ClientApp\node_modules\vimeo\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
> 	- install 'stream-http'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "http": false }
> 
> 
> ERROR in ./node_modules/vimeo/lib/vimeo.js 21:18-34
> 
> Module not found: Error: Can't resolve 'https' in 'E:\ClientApp\node_modules\vimeo\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
> 	- install 'https-browserify'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "https": false }
> 
> 
> ERROR in ./node_modules/vimeo/lib/vimeo.js 22:9-22
> 
> Module not found: Error: Can't resolve 'fs' in 'E:\ClientApp\node_modules\vimeo\lib'
> 
> 
> ERROR in ./node_modules/vimeo/lib/vimeo.js 23:11-26
> 
> Module not found: Error: Can't resolve 'path' in 'E:\ClientApp\node_modules\vimeo\lib'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
> 	- install 'path-browserify'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "path": false }

	
Do I need to install any dependency?	

Thank You

**Comment by aaronm67** [comment]
It looks like you're trying to use the library on a frontend client - this library is not intended for frontend use.

You should never deploy your vimeo token and secret in client code, which is a requirement for this library.

**Comment by edotappstore** [comment]
oh that's strange because i am already using this library in one of my project which has lower react version.

Anyways its a good practice to handle this from server
@aaronm67  Can u suggest any vimeo library for .NET?

i cant find the one mentioned in the doc.

https://developer.vimeo.com/api/libraries

**Comment by aaronm67** [comment]
Note that any recommendations here are unofficial, so support would come from the repository, not from Vimeo.

That said - this is a popular library that is well maintained https://github.com/mfilippov/vimeo-dot-net
