### ISSUE TITLE
New API calls does not seems to work with 3.0 version

### ISSUE THREAD

**Issue by dotansimha** [vimeo/vimeo.js#18]
Hi,
I am trying to use "POST /videos/{id}/pictures" call in order to update the default thumbnail of a video.
Using the current version of vimeo-api, the only response I get is "The app is not allowed to perform this actions". 
When updating the version that the library sends to 3.2 - The actions works great. 
Is there a reason for not updating the version? 

Thanks!

**Comment by Dashron** [comment]
Hi dotanshimha,

Did the solution work for you?
