### ISSUE TITLE
vimeo sdk 2.x support

### ISSUE THREAD

**Issue by jessetabak** [vimeo/vimeo.js#185]
Hi,

My vimeo script is still using the deprecated vimeo 2.x SDK.
How long can I expect the 2.x version to keep working?

Thanks.

**Comment by hedyyytang** [comment]
The 2.x SDK is moved to `@vimeo/vimeo` - `https://www.npmjs.com/package/@vimeo/vimeo`. You can keep using @vimeo/vimeo version 2.x, we have no plan to deprecate that.
