### ISSUE TITLE
Not sure how to pass token on single-user application

### ISSUE THREAD

**Issue by adamgins** [vimeo/vimeo.js#19]
I am trying  to access Vimeo to upload some videos using single-user mode (as per https://developer.vimeo.com/api/authentication#authenticated-requests) 

```
var lib = new Vimeo(MYPARAM1, MYPARAM2, MYPARAM3);
var vimeoAccessToken = MYPARAM3; // this was generated from the API Console

var scopes = ["public","private","purchased","create","edit","delete","interact","upload"];
var state = Random.id();
var redirect_uri = "http://localhost:3000/_oauth/vimeo"
var url = lib.buildAuthorizationEndpoint(redirect_uri, scopes, state);
console.log("vimeo url",url);
```
This prints out the URL ... it's a loooong string starting with ` https://api.vimeo.com/oauth/authorize?response_type=code&client_id=` and looks good (I think?). 

I am not sure how to authenticate, as the example talks about a user clicking on something to get a "code"... as this is server based, there's no user interaction.

When I try and run a test:

```
lib.streamingUpload('/Users/adamginsburg/Movies/Copter.m4v',  function (error, body, status_code, headers) {
    if (error) {
        console.log(error);

        throw new Meteor.Error("Vimeo Upload Error", error);
    } else {
        console.log(body)
        console.log(status_code)

        lib.request(headers.location, function (error, body, status_code, headers) {
            console.log(body);
        });
    }

});

```

I get an error: `"[Error: {"error":"A valid user token must be passed."}]"`

Any help, please?

**Comment by Dashron** [comment]
Authorization endpoints are used by multi user applications generating access tokens on demand.

Single user applications generate their access tokens on the app page, instead of through the authorization endpoints.

You should be able to skip all of the authorization code and just use the following:

```
var lib = new Vimeo(client_id, client_secret, access_token);
lib.streamingUpload('/Users/adamginsburg/Movies/Copter.m4v',  function (error, body, status_code, headers) {
    if (error) {
        console.log(error);

        throw new Meteor.Error("Vimeo Upload Error", error);
    } else {
        console.log(body)
        console.log(status_code)

        lib.request(headers.location, function (error, body, status_code, headers) {
            console.log(body);
        });
    }

});
```

**Comment by adamgins** [comment]
Thanks for the quick response. That's what I tried intially, I still get ` [Error: {"error":"A valid user token must be passed."}]`

I was thinking I need to authenticate, somewhere in between the `new Vimeo` and `lib.streaming` calls

**Comment by adamgins** [comment]
BTW, If I call:

```
var scopes = ["public","private","purchased","create","edit","delete","interact","upload"];
var state = Random.id();
var redirect_uri = "http://localhost:3000/_oauth/vimeo"
var url = lib.buildAuthorizationEndpoint(redirect_uri, scopes, state);
console.log("vimeo url",url);


HTTP.call("POST", url,

    function (error, result) {
        if (!error) {
            console.log(result);
        } else {
            console.log(error)
        }
    });
```
It seems to work, I get a `302` response code.

**Comment by adamgins** [comment]
I was thinking I need to somehow add `curl -H "Authorization: bearer <OAUTH_TOKEN>" https://api.vimeo.com` into the request???

**Comment by Dashron** [comment]
The url from the authorization endpoint is meant for a user interacting with your web app. You can read more here: https://developer.vimeo.com/api/authentication#generate-redirect.

The `Authorization: bearer <access_token>` header is automatically added (https://github.com/vimeo/vimeo.js/blob/master/lib/vimeo.js#L178-L182) if you provide your access token to the third parameter in the constructor.

Try logging out your request options (https://github.com/vimeo/vimeo.js/blob/master/lib/vimeo.js#L107) and make sure that the access token is set.

If the access token is set, and you still see `[Error: {"error":"A valid user token must be passed."}]` you should send us the access token you are using through our contact form at https://vimeo.com/help/contact. (I notice you already have an open ticket, so you can just reply to that email)

**Comment by adamgins** [comment]
Ah thanks.. will send through access token now
