### ISSUE TITLE
Sorry, but where is the typescript support?

### ISSUE THREAD

**Issue by mattiLeBlanc** [vimeo/vimeo.js#190]
Hi,

I got notified to use `@vimeo/vimeo` now in in NPM instead of `vimeo` but I am having issues with missing typescript declarations.
Where is the typescript support in this library, I can't really believe people would not see the benefit of using TS over JS in 2023.

**Comment by aaronm67** [comment]
Adding type declarations isn't planned at this time.

**Comment by mattiLeBlanc** [comment]
Well that is not very good. The old library had declarations (Vimeo 2.1), why can't you port them? You are suggesting us to upgrade but we actually get issues because I and many other developers utilise Typescript.

**Comment by aaronm67** [comment]
Type declarations weren't in 2.1, you may have used some library to generate them, or you may have ignored the missing declarations.

Going to lock discussion here, we'll provide an update if this makes it onto the roadmap at any point.
