### ISSUE TITLE
File descriptor not closed while uploading a video

### ISSUE THREAD

**Issue by mbeguin** [vimeo/vimeo.js#20]
Hi, 

Thanks for your work on this project.

I'm running on an issue using the **FileStreamer** through the **streamingUpload** method, after uploading the video, the video file is locked and can't be removed. This is probably due to the video file descriptor which is not closed while the upload is done.

Adding the following line when the upload is done solves the problem. (tested on version 0.10.35)
```javascript
fs_module.close(_self._fd);
```

What do you think ?

Hope it helps.

**Comment by Dashron** [comment]
Looks great. I'll test the change and push it up asap.

**Comment by Dashron** [comment]
https://github.com/vimeo/vimeo.js/commit/a5f105ba76f4f3d6938c7b57e24f79160e2d3941

Let me know if you run into more issues!

**Comment by mbeguin** [comment]
Thank you. I'll be able to test it soon. I'll let you know.
Thanks for the fast answer.
