### ISSUE TITLE
No Content-Length header in POST request

### ISSUE THREAD

**Issue by johnnycrab** [vimeo/vimeo.js#23]
See problems here: 
https://vimeo.com/forums/api/topic:265764

and here:
http://stackoverflow.com/questions/29954095/vimeo-api-for-node-js-html-error-sorry-vimeo-will-be-right-back/29992716#29992716

The stackoverflow link also features my answer. The link to my repo with the potential bugfix is here: https://github.com/johnnycrab/vimeo.js

What do you think? I can also create a pull request, if needed.

Thanks!
Johnny

**Comment by Dashron** [comment]
We're working on fixing the server to actually allow these requests, but this is a great temporary fix. Specifically the following fix the issue:

https://github.com/vimeo/vimeo.js/compare/master...johnnycrab:master#diff-a5a4dd424b43c7cb37c123a90263d75aR105

through 

https://github.com/vimeo/vimeo.js/compare/master...johnnycrab:master#diff-a5a4dd424b43c7cb37c123a90263d75aR130

**Comment by Dashron** [comment]
We're still working on the server side fix. I'll be monitoring my email throughout the night and will update this thread when everything is back to normal.

**Comment by Dashron** [comment]
Unfortunately the server fix is taking longer than expected. I've made some small changes to the library (thanks for example code @johnnycrab) that will resolve the problem until everything is back to normal.

Make sure you are running at least 1.1.3 if you are encountering this problem.

**Comment by yossavi** [comment]
still get the same problem with vimeo@1.1.3

**Comment by johnnycrab** [comment]
When calling which api request exactly do you still get the error?

**Comment by yossavi** [comment]
var Vimeo = require('vimeo').Vimeo;
var lib = new Vimeo('--------', -------', '-------');
lib.streamingUpload(files[0].fd, function (err, body, status_code, headers) {
	if (err) {
// here I get the error
	    console.log(err);
	    return res.serverError("Server Error");
	}
....

**Comment by johnnycrab** [comment]
and the error you are getting is this "sorry, vimeo will be right back" html page?

**Comment by yossavi** [comment]
yes

**Comment by johnnycrab** [comment]
Can you run this code and tell me if you get an upload ticket?

```javascript
var https = require('https');

var req = https.request({
	protocol : 'https:',
	hostname: 'api.vimeo.com',
	path: '/me/videos',
	port : 443,
	method : 'POST',
	headers : {
		'Accept': "application/vnd.vimeo.*+json;version=3.2",
		'Content-Type': 'application/json',
		'User-Agent': 'whatever',
		'Content-Length': 20,
		'Authorization': 'bearer HERE_YOUR_ACCESS_TOKEN'
	}
}, function (res) {
	res.on('data', function (d) {
		console.log(d.toString());
	});
});

req.write('{"type":"streaming"}');

req.end();
```

**Comment by yossavi** [comment]
yes, I got an upload ticket

**Comment by Dashron** [comment]
I'm noticing timeouts (we're restarting the upload server 1511655188.cloud.vimeo.com soon), but I can't replicate the 503 error anymore.

Try the above code from @johnnycrab and then try the following, the same request from within the library:

```JS
var Vimeo = require('vimeo').Vimeo;
var lib = new Vimeo(client_id, client_secret)
lib.access_token = your_token;
lib.request({
    method: "POST",
    path: "/me/videos",
    query: {type: "streaming"}
}, function (err, resp) {
    console.log(err);
    console.log(resp);
});
```

**Comment by johnnycrab** [comment]
I can't replicate the 503 anymore either...

**Comment by Dashron** [comment]
Also, from within the directory of your script, can you send me the contents of `npm list`

**Comment by yossavi** [comment]
@Dashron your code is also working, but I don't understand where I should actually uploading the video.
My npm list is too long i'm afraid, is there anything that interest you in particular?

**Comment by Dashron** [comment]
I wanted to double check the version of the `vimeo` package. That list is the most accurate way to tell exactly which version your current code is accessing, because npm can look in a couple of different locations for the library.

So the upload ticket works, but the `streamingUpload` method doesn't? Can you send me the exact output you receive from that method?

**Comment by johnnycrab** [comment]
Furthermore, if I may add two things:
1.) Do you get the error right away, or is it already uploading?
2.) The code you posted passes in `files[0].fd` to the upload method. It should throw an error much earlier, but just to be sure: Are you passing in a path? Because `fd` implies some sort of file descriptor...

**Comment by yossavi** [comment]
in npm list it says: vimeo@1.1.3

the error that I get is the html error with:
<title>Sorry. Vimeo will be right back.</title>
...
<h2>Something is weird in the magical forest.</h2>
<p>We&rsquo;ll be back in a jiffy.</p>

I don't get the error right away, it's takes sometime.

I'm passing a path, of course.
this code worked for me two weeks ago, in windows and in ubuntu, now it doesn't.

**Comment by yossavi** [comment]
I tried to run it now in ubuntu and I got:

/home/git/moula/api/v1/node_modules/vimeo/lib/vimeo.js:114
                request_options.headers['Content-Length'] = Buffer.byteLength(request_option
                                                                   ^
TypeError: Argument must be a string
    at Vimeo.vimeo_request [as request] (/home/git/moula/api/v1/node_modules/vimeo/lib/vimeo.js:114:54)
    at FileStreamer._user_ready (/home/git/moula/api/v1/node_modules/vimeo/lib/vimeo.js:396:19)
    at /home/git/moula/api/v1/node_modules/vimeo/lib/filestreamer.js:78:19
    at /home/git/moula/api/v1/node_modules/vimeo/lib/filestreamer.js:220:20
    at IncomingMessage.<anonymous> (/home/git/moula/api/v1/node_modules/vimeo/lib/filestreamer.js:263:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)

**Comment by johnnycrab** [comment]
Ah, alright. Can you try the code in my fork, please: https://github.com/johnnycrab/vimeo.js . The library is doing a DELETE request without any data, so probably `undefined` is getting passed to Buffer.byteLength. My code's doing a check for the body.

**Comment by Dashron** [comment]
Nice catch, fixing now.

**Comment by johnnycrab** [comment]
What node version are you running on ubuntu? node v0.12 for example returns '9' when calling Buffer.byteLength with undefined. So effectively the DELETE request is being called with Content-Length: 9

**Comment by yossavi** [comment]
now it's work well in widows 8.1 and Ubuntu 14.04.2 both with node v0.12.0
thanks!!!

**Comment by Dashron** [comment]
I'm on iojs 1.6.1 and can reproduce his error. I get the feeling that a non-zero content length, but with no content sent is dying on our intermediate services

**Comment by Dashron** [comment]
Just published 1.1.4. Should solve the issue with empty deletes

**Comment by johnnycrab** [comment]
:thumbsup:

**Comment by apatinoyu** [comment]
Has it been fixed? I got same issues with vimeo 1.1.4  and 1.1.3 version

**Comment by johnnycrab** [comment]
It should be. My production apps haven't experienced this issue since then. Can you elaborate on your problems?

**Comment by apatinoyu** [comment]
I'll let you know, I am trying with vimeo 1.2.0

**Comment by apatinoyu** [comment]
I got an issue : <meta charset="utf-8">
    <meta name="robots" content="nofollow, noindex">
    <title>Sorry. Vimeo will be right back.</title>

    <style>
        body {
            margin: 0;
            padding: 0;
            background: #34454E url('http://a.vimeocdn.com/images_v6/ins_down_illustration.png') bottom repeat-x fixed;
            color: #ffffff;
            font: 36px/1.3 Helvetica, Arial, sans-serif;
            text-align: center;
        }
...
..
with vimeo: "1.2.0"
I am doing many requests to the method : "get", path   : '/users/' 
Wich version are you using?

**Comment by johnnycrab** [comment]
I am currently using my own fork (https://github.com/johnnycrab/vimeo.js) (which needs to be updated to the current upstream version though). The in production projects that are currently running are basically uploading and editing videos around the clock and I have no issues. So maybe you'd like to try my fork, and if it works, I can figure out the problem and maybe file a pull request?

**Comment by apatinoyu** [comment]
Yes, is weird . sometimes It doesnt throw the error and sometimes yes.
But I am going to try to install again the module. let's see . :)

**Comment by apatinoyu** [comment]
Well.. the web https://developer.vimeo.com/api/spec is down too :/

**Comment by tommypenner** [comment]
Response times from the Vimeo API are currently slow or timing out. Vimeo engineers are investigating, updates here:

https://vimeo.com/forums/api/topic:280946
https://twitter.com/vimeoapi

**Comment by johnnycrab** [comment]
Good to know! Thanks for the update!
