### ISSUE TITLE
npm out of date

### ISSUE THREAD

**Issue by puckey** [vimeo/vimeo.js#24]
Can you publish the latest version of this library to NPM? The NPM version does not currently include the latest fixes for file uploads...

**Comment by Dashron** [comment]
Are you using `vimeo` or `vimeo-api`? `vimeo-api` is deprecated, and has a deprecation warning. All updates will be pushed to `vimeo`

**Comment by puckey** [comment]
ahh didn't spot that - thanks!

**Comment by puckey** [comment]
You might want to add a deprecation warning to the following page: https://www.npmjs.com/package/vimeo-api

(which is what you reach when you google 'vimeo api npm')

**Comment by Dashron** [comment]
Deprecation warnings were added to the lib, but it turns out those warnings don't always show. I hacked together a solution (and had to sully the commit history in the process haha)
