### ISSUE TITLE
streamingUpload: allow passing of options

### ISSUE THREAD

**Issue by puckey** [vimeo/vimeo.js#25]
I am using streamingUpload to upload videos, but would like to set the 'upgrade_to_1080' option to true.. as far as I can see, this is currently impossible

**Comment by Dashron** [comment]
I'll add it, in the meanwhile you can set the parameter here: https://github.com/vimeo/vimeo.js/blob/master/lib/vimeo.js#L388

**Comment by pantos27** [comment]
was this added?

**Comment by erunion** [comment]
Not in `master`, but it's coming with our v3.4 API and 2.2.0 SDK release later this week.

https://github.com/vimeo/vimeo.js/pull/58
