### ISSUE TITLE
Content-Length needs to be set when sending empty PUTs etc.

### ISSUE THREAD

**Issue by johnnycrab** [vimeo/vimeo.js#27]
Hey,
I had been experiencing problems when for example setting the video presets of a single video. This is done via a PUT request to the appropriate path, however without any body. Node.js sets a Transfer-Encoding:chunked header, as there is no content-length specified (we hadn't been setting the content-length header on empty-body requests).  
So the API server responds with a 411, stating that Transfer-Encoding:chunked is not supported.

A fix would be to explicitly set `Content-Length:0` when dealing with PUT / PATCH / POST / DELETE requests. 

https://github.com/johnnycrab/vimeo.js/commit/a7b61d774fc511e96ea260cb68493e1eb91a25ff?diff=unified 

shows a possible fix. I made a comment on the needed line.

What do you think?

**Comment by Dashron** [comment]
Looks good for your branch, but I think this is already covered by the changes made back during the whole 503 problem: https://github.com/vimeo/vimeo.js/blob/master/lib/vimeo.js#L114-L118.

The 411 error is the replacement for that 503 error, to finally give clear error messages to node users.

Let me know if I'm totally off base here, I'll give the official lib another check when I get into the office.

**Comment by johnnycrab** [comment]
Oh yes, you're right. Sorry, I should have compared my branch to the lib first, didn't know you had made other final changes.
