### ISSUE TITLE
streamingUpload no longer working

### ISSUE THREAD

**Issue by danecando** [vimeo/vimeo.js#28]
Recent changes to the API?

I've been using this API in my application for a while now and all of the sudden I'm getting an error when I try to upload a video. 

streamingUpload is no longer working for me and I am receiving the following error: The Vimeo API does not currently support Transfer-Encoding: chunked. Contact us at https://vimeo.com/help/contact if you have any questions.

I'm not sure what the issue is here. The file is completely intact on the system and everything in the code is correct like it was and has been working until recently. No changes to anything on the server, or the project itself.

**Comment by Dashron** [comment]
This change happened a couple of weeks ago. Update to the latest version of the `vimeo` library for a fix!

**Comment by danecando** [comment]
Thanks @Dashron
