### ISSUE TITLE
Irregularly getting OpenSSL unknown protocol errors when uploading

### ISSUE THREAD

**Issue by johnnycrab** [vimeo/vimeo.js#30]
Sometimes when uploading, I'm getting the following error:

```
write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:782
```

"Irregularly" means quite often, but not always.
Any ideas why this is happening?

Cheers!

**Comment by johnnycrab** [comment]
This is happening in mid-upload. However I have seen that I'm running on node v0.12.3. I'll update and check if this is still happening.

**Comment by Dashron** [comment]
Let me know what you see. Also, if you can provide the hostname of the upload server, it might narrow down the cause.

**Comment by johnnycrab** [comment]
I haven't seen this problem occuring for quite a while now... Sorry for not getting back to you. I'm closing this issue for now. :)
