### ISSUE TITLE
How to get progress of the upload?

### ISSUE THREAD

**Issue by gino8080** [vimeo/vimeo.js#33]
How to use the upload request or streamingUpload method and get the bytes loaded to create a sort of progress bar?

**Comment by Dashron** [comment]
This is an item we would like to support, but have not yet implemented. The overall upload process is described below, followed by suggestions how you might integrate progress.

1. The core upload code starts here: https://github.com/vimeo/vimeo.js/blob/master/lib/filestreamer.js#L183. This request includes headers that describe how much of the file we intend to upload. 

2. We send the file contents here: https://github.com/vimeo/vimeo.js/blob/master/lib/filestreamer.js#L188, and will continue to stream until the file is complete, or we encounter an error. 

3. If step 2 encounters an error (such as a timeout, or a server error), we ask the server how much of the file was successfully uploaded here: https://github.com/vimeo/vimeo.js/blob/master/lib/filestreamer.js#L205. If this new request fails, we throw an error up the chain. If the request passes we continue back to step 1 above with that new starting point.

4. If step 2 does not encounter an error, we complete the upload here: https://github.com/vimeo/vimeo.js/blob/master/lib/vimeo.js#L404

**Comment by gino8080** [comment]
Thank you I did it !

so sorry for my dirty code , maybe it can be useful for you to integrate, here is 
https://github.com/vimeo/vimeo.js/pull/34

**Comment by nishadhasan** [comment]
Can you please give me a progress bar solution for POST method in PHP for Direct Video Upload on Vimeo?

**Comment by erunion** [comment]
This library currently only supports getting progress information on uploads when using the `upload` (and `tus` upload approach).

See the `progressCallback` argument documentation here: https://github.com/vimeo/vimeo.js#uploading-videos
