### ISSUE TITLE
tus Upload Protocol

### ISSUE THREAD

**Issue by r-a-y** [vimeo/vimeo.js#36]
I read that [Vimeo is using](http://tech.eu/features/6672/transloadit-tus-protocol-vimeo/) the [tus](https://github.com/tus/tus-resumable-upload-protocol) protocol for resumable uploads.  Is this something that will work its way down to the Vimeo JS API eventually?

**Comment by Dashron** [comment]
It is not yet supported in the API, but we will support it in the future, and update all of our libraries to accommodate it.
