### ISSUE TITLE
Question: Setting Acess Token for Multi-User authentification

### ISSUE THREAD

**Issue by renarsvilnis** [vimeo/vimeo.js#37]
Hi,
by the examples it is not clear to how to set handle user specific access-token in a multi-user authentification scenario.

The library example and docs show setting `lib.access_token = token.access_token` after successfully receiving it, this rises some questions:

1. But what happens when an other user authenticates? Doesn't the `lib.access_token` get overwritten by the new user `access_token`?
2. Should I just create ` new Vimeo(...)` instance on each request and store the token in a session?

Using `express` in the example below.

```javascript
// ... constant declaration

const vimeo = new Vimeo(VIMEO_CLIENT_ID, VIMEO_CLIENT_SECRET);

// renders a link that redirects the user to vimeo auth
app.get('/', (req, res, next) => {
  const vimeoState = 1; // TODO: change to generate random string
  const loginUrl = vimeo.buildAuthorizationEndpoint(VIMEO_REDIRECT_URL, VIMEO_SCOPES, vimeoState);
  res.render('index', {loginUrl});
});

// handle response
app.get('/auth', (req, res, next) => {
  const code = req.query.code;
  const state = req.query.state;

  vimeo.accessToken(code, VIMEO_REDIRECT_URL, (err, token) => {
    if (err) { return next(err); }
    
    if (token.access_token) {
      // Note: what to do if multiple users connected?
      vimeo.access_token = token.access_token;
      req.session.vimeo = {token};
    }
  });
});
```

**Comment by Dashron** [comment]
It depends on your use case.

If all of your Vimeo API requests will be authenticated as a single user (such as if you are building a website that only makes API calls to retrieve https://vimeo.com/dashron's videos) then you can create the library outside of the routes and assign the access token there too.

If your Vimeo API requests will be authenticated by different users depending on who is using your website, you should construct a new Vimeo object within each route, such as below:

```js
// renders a link that redirects the user to vimeo auth
app.get('/', (req, res, next) => {
  const vimeo = new Vimeo(VIMEO_CLIENT_ID, VIMEO_CLIENT_SECRET);
  const vimeoState = 1; // TODO: change to generate random string
  const loginUrl = vimeo.buildAuthorizationEndpoint(VIMEO_REDIRECT_URL, VIMEO_SCOPES, vimeoState);
  res.render('index', {loginUrl});
});

// handle response
app.get('/auth', (req, res, next) => {
  const vimeo = new Vimeo(VIMEO_CLIENT_ID, VIMEO_CLIENT_SECRET);
  const code = req.query.code;
  const state = req.query.state;

  vimeo.accessToken(code, VIMEO_REDIRECT_URL, (err, token) => {
    if (err) { return next(err); }

    if (token.access_token) {
      // Note: what to do if multiple users connected?
      vimeo.access_token = token.access_token;
      req.session.vimeo = {token};
    }
  });
});
```

**Comment by renarsvilnis** [comment]
Thanks, just as I thought.
Also note for anyone reading it: Good idea to wrap the `Vimeo` instance creation in an [factory-function](https://www.youtube.com/watch?v=ImwrezYhw4w). So you won't need to reference the `client_id`, ... all the time.

**Comment by Dashron** [comment]
Totally agree about the factory function. In my personal work I tend to have something like...

**/src/lib/Vimeo.js**
```js
const config = require('config');
const Vimeo = require('vimeo');

module.exports = function getVimeoLib () {
    return new Vimeo(config.get('vimeo.client_id'), config.get('vimeo.client_secret'));
};
```

Which my code can use like this:

```js
var lib = require('./src/lib/vimeo.js').getVimeoLib();
// use the lib
```
