### ISSUE TITLE
Not sure how to get thumbnail image of private videos

### ISSUE THREAD

**Issue by shivmishra** [vimeo/vimeo.js#39]
Hi i am using that code to get thumbnail image of video
$.ajax({
url: 'vimeo.com/api/v2/video/'; + id + '.json',
dataType: 'jsonp',
success: function (data) {
$("#file" + fileid).attr('src', data[0].thumbnail_large);
}
});
its working for public video but for private video its not working. can anyone help ??

**Comment by Dashron** [comment]
The url you provided is part of the advanced api, which requires additional authentication information. This API has been deprecated. You must use the new API here: https://developer.vimeo.com/api. 

Unfortunately we do not currently have an official client side library. We plan on supporting client side interactions in the future, but at the moment there is not a completely secure option available.
