### ISSUE TITLE
viewcounter is not correct 

### ISSUE THREAD

**Issue by rayway30419** [vimeo/vimeo.js#40]
Hi all,

I use `Video.get_info` to get information about videos, and the return value `number_of_plays` is 0.

I check it with vimeo api playground, the api(below) return the correct value.

`https://developer.vimeo.com/api/playground/videos/{video_od}`

**Comment by Dashron** [comment]
Which library are you using? I can not find `Video.get_info` in any part of this library.

**Comment by rayway30419** [comment]
Oops,

**Comment by rayway30419** [comment]
My fault, not this repo. :(
