### ISSUE TITLE
https://player.vimeo.com/api/player.js is inaccessible!!

### ISSUE THREAD

**Issue by gino8080** [vimeo/vimeo.js#43]
Since some hours 
https://player.vimeo.com/api/player.js
is not accessible anymore 
so individual players returns this error:

Refused to execute script from 'https://player.vimeo.com/api/player.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by Dashron** [comment]
We had some downtime last week. Are you still encountering this issue?

**Comment by sulym-roman** [comment]
Seems that now it is happening again?

**Comment by Dashron** [comment]
Are you still seeing this issue? We had some down time again over the Holidays.

For anyone reading this in the future, make sure to check https://status.vimeo.com to make sure Vimeo has not reported any downtime.

**Comment by sulym-roman** [comment]
Seems to be ok now. How often do you have "down times"?

**Comment by Dashron** [comment]
Down time was the wrong term to use, this situation was an unexpected service outage. Service outages are rare.
