### ISSUE TITLE
quickest API request to check if video exists?

### ISSUE THREAD

**Issue by colmose** [vimeo/vimeo.js#47]
Is there a quick (unauthenticated, preferably) route to hit to check if a video exists? 

Currently using the `https://vimeo.com/api/oembed.json?url=https://vimeo.com/[video-id]` route but don't really need the metadata json, just want to see if a video exists.

**Comment by Dashron** [comment]
Will you be making this request in the browser or on the backend?

**Comment by colmose** [comment]
On the backend, from a node.js server

**Comment by Dashron** [comment]
I just ran some tests, and I think doing a HEAD request instead of a GET request to that same oEmbed endpoint should work. You can use the status code to tell if the video is real or not.

**Comment by colmose** [comment]
Perfect, I'm doing a HEAD request alright. Just wanted to check if there was some obscure route that I hadn't tested. 

Many thanks.
