### ISSUE TITLE
Where is vimeo_id?

### ISSUE THREAD

**Issue by nabeards** [vimeo/vimeo.js#50]
I feel like I'm missing something simple: where is the video_id field in the responses from the Vimeo API? Should I be parsing that out separately from the URI?

**Comment by Dashron** [comment]
The Vimeo API does not expose numeric ids. The URI can be used as a globally unique identifier across all resource types.

What is your use case for needing an ID?

**Comment by nabeards** [comment]
I thought the URI would work as well, but I'm getting multiple versions of the URI from the API:
`/videos/209292292:538e87f31b`
and
`/videos/209292292`
are the same video, but I get them as two separate entities.

I couldn't find anything about the
`:{number}`
in the docs to tell me what it means.

This is why I figured I would need to parse that ID out and use it instead of the full URI. Thoughts?

**Comment by nabeards** [comment]
I've posted this same question on the Vimeo forum: https://vimeo.com/forums/api/topic:288304

**Comment by Dashron** [comment]
The value after the colon is necessary for the "via direct link only" privacy option. I believe you should always be getting a URI with the colon and extra data. Anything else is likely a bug.

Can you describe where you are finding the /videos/209292292 format?

**Comment by nabeards** [comment]
Almost all of my video URIs are in the /videos/209292292 format (no colon). Only about 5% come through with the colon. And, I get both every time for the ones that do have a colon.

This is coming directly over the `/me/videos` endpoint.

**Comment by Dashron** [comment]
Under what conditions do you record the URI? Is it possible that you recorded the URI before the video was "via direct link only", and after the privacy was enabled?

**Comment by nabeards** [comment]
Additional info: the video objects without a colon report privacy.view as 'unlisted'. The video objects with a colon report privacy.view as 'disabled'.

Privacy settings are the same in the Vimeo Pro interface for both types of video objects:
<img width="253" alt="screen shot 2017-04-03 at 6 32 26 pm" src="https://cloud.githubusercontent.com/assets/764686/24634427/f0a0cf98-189b-11e7-88a5-471799f4bd9d.png">

Still not understanding why I get both URIs for these videos.

**Comment by Dashron** [comment]
I'll get someone to dig into this deeper, and will let you know when we have an update!

**Comment by nabeards** [comment]
> Under what conditions do you record the URI? Is it possible that you recorded the URI before the video was "via direct link only", and after the privacy was enabled?

Hm, this I am not sure of. But, are you then saying that changing privacy on a video changes the URI identifier of the video? That seems, well, kinda wrong to me, and it means that the URI is not really a reliably unique identifier for the video going across requests.

**Comment by Dashron** [comment]
For the user who does not own the video, we consider the "direct link" privacy change to fundamentally change the video. We are removing access to the old video and requiring it to be re-assessed in another way.

I don't think this needs to apply to the video owner. In the case of the authenticated user owning the video, It might make sense to always give the version without the colon so that there's stronger consistency. I'll do more research and get back to you.

**Comment by Dashron** [comment]
It appears it does not currently work as I described above. Even the owner must use the colon url. 

I'm going to do some more research and see if we can make the change.

**Comment by nabeards** [comment]
I ended up writing a custom wrapper when I receive the URI, removing anything from the `:` on.
