### ISSUE TITLE
The library doesn't checks for rate limiting

### ISSUE THREAD

**Issue by ZaDarkSide** [vimeo/vimeo.js#52]
This library should check if [rate limiting](https://developer.vimeo.com/guidelines/rate-limiting) is in effect and not to hammer the API.

It could be an enhancement, that will allow developers to avoid the hassle of implementing their own method by parsing the headers.

**Comment by jehartzog** [comment]
I recently implemented a complete rate limiting addon when using this library and found some issues with this library that actually makes it challenging to implement your own rate limiting. Please see #51, but basically the current documentation doesn't give you enough correct info to avoid extremely low rate limits.
