### ISSUE TITLE
The upload server returned a non 200 http status code

### ISSUE THREAD

**Issue by Gamec** [vimeo/vimeo.js#55]
Hey,

I'm using Vimeo.js for uploads in my app. It was all working very well up until today. All uploads return this error now:

```
Error: {"error":"Unable to complete video upload. Please get in touch with the app's creator.","link":null,"developer_message":"The upload server returned a non 200 http status code.","error_code":4011}
  at IncomingMessage.<anonymous> (/home/xxxx/node_modules/vimeo/lib/vimeo.js:162:15)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:80:11)
  at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Any idea what can it be?

**Comment by jehartzog** [comment]
We started getting this last night at 10:30pm EST, most likely they are having some other temporary issue with their API service.

**Comment by erunion** [comment]
Sorry about that! We had some errant issues with a deploy in the API, but they should all be resolved as of late last night. Let us know if you're still experiencing these.

**Comment by brainslcdevshop** [comment]
Hello @erunion I have same error!

**Comment by erunion** [comment]
@brainslcdevshop Are you still seeing it?
