### ISSUE TITLE
Option to set the video's title in the upload function

### ISSUE THREAD

**Issue by Donqvolf** [vimeo/vimeo.js#56]
The title says all. It's possible to set the video's title (actually, it is always "**undefined**") through the function of upload?  
  
Many thanks,  
João Pedro Viana.

**Comment by erunion** [comment]
With the upload methods we've supplied in this library, no, but you can send a `PATCH` request to the video URI after uploading is complete to update the title.

Check out the `name` parameter on https://developer.vimeo.com/api/endpoints/videos#PATCH/videos/{video_id}
