### ISSUE TITLE
Setting paramaters of an upload

### ISSUE THREAD

**Issue by pantos27** [vimeo/vimeo.js#60]
If I would like to upload a video that should be private what would be the prefered way?

Call POST on **/me/videos** and then upload to a specific uri?

Should all these option be passed into query?
        ```
{
            description : "some description",
            name : 'name name name',
            privacy : {
                add : true,
                download : true,
                embed : "private",
                view : 'unlisted'
            }


```

**Comment by tommypenner** [comment]
Video metadata cannot be set until after the upload has completed. To edit metadata, perform a PATCH to its uri with the metadata in the request body. Documentation here: https://developer.vimeo.com/api/endpoints/videos#PATCH/videos/{video_id}

**Comment by erunion** [comment]
This is actually coming with our 2.0.0 SDK release later this week, or you can do the `PATCH` route. https://github.com/vimeo/vimeo.js/pull/58
