### ISSUE TITLE
how to send data using post man

### ISSUE THREAD

**Issue by nikunjprajapati77** [vimeo/vimeo.js#63]
please help me about it

i get this error
**POST /users/uploadvideo 200 47.563 ms - 12
/opt/lampp/htdocs/beyond1/node_modules/vimeo/lib/vimeo.js:445
    } else if (fileSize > response.upload_quota.space.free) {
                                                ^
TypeError: Cannot read property 'space' of undefined
    at /opt/lampp/htdocs/beyond1/node_modules/vimeo/lib/vimeo.js:445:49
    at IncomingMessage.<anonymous> (/opt/lampp/htdocs/beyond1/node_modules/vimeo/lib/vimeo.js:177:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[nodemon] app crashed - waiting for file changes before starting...**

**Comment by erunion** [comment]
It sounds like the Vimeo Application you have set up has not yet been authorized for upload to accounts that are not your own.

If you go into your developer application settings, and click the **Request Upload Access** link:

![screen shot 2018-02-09 at 10 06 25 pm](https://user-images.githubusercontent.com/33762/36058012-93eebc3e-0de5-11e8-9b17-4541615273ec.png)

Fill out the form on that page and our support team will get you on your way.

If you still have trouble, feel free to contact our support team at https://vimeo.com/help/contact.

**Comment by nikunjprajapati77** [comment]
hello sir
now i have access token : d09840fe8b57e4fe041c7dccbc65e182
but i can not upload video

# error
**Request** 
Request URL:http://localhost/videos/beyond/vimeo-upload-master/undefined
Request Method:PUT
Status Code:405 Method Not Allowed
Remote Address:[::1]:80
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Accept-Ranges:bytes
Connection:Keep-Alive
Content-Language:en
Content-Type:text/html; charset=utf-8
Date:Sat, 17 Feb 2018 05:54:54 GMT
Keep-Alive:timeout=5, max=100
Server:Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/5.6.30 mod_perl/2.0.8-dev Perl/v5.16.3
Transfer-Encoding:chunked
Vary:accept-language,accept-charset
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-GB,en-US;q=0.9,en;q=0.8
Connection:keep-alive
Content-Length:2521709
Content-Range:bytes 0-2521708/2521709
Content-Type:video/mp4
Cookie:ci_session=a%3A12%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%223291fdd8e7acb23a9619c74e014737dc%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A3%3A%22%3A%3A1%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A105%3A%22Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F63.0.3239.108+Safari%2F537.36%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1514955442%3Bs%3A9%3A%22user_data%22%3Bs%3A0%3A%22%22%3Bs%3A15%3A%22team_profile_id%22%3Bs%3A1%3A%221%22%3Bs%3A21%3A%22team_profile_uniqueid%22%3Bs%3A13%3A%22576393c58ba8f%22%3Bs%3A22%3A%22team_profile_full_name%22%3Bs%3A13%3A%22Administrator%22%3Bs%3A18%3A%22team_profile_email%22%3Bs%3A22%3A%22admin%40technostacks.com%22%3Bs%3A22%3A%22team_profile_groups_id%22%3Bs%3A1%3A%221%22%3Bs%3A28%3A%22team_profile_avatar_filename%22%3Bs%3A17%3A%22576393c58ba8f.png%22%3Bs%3A11%3A%22groups_name%22%3Bs%3A13%3A%22Administrator%22%3B%7Dbba147ffad886cf8a2ef00b4002bed61; _ga=GA1.1.285661838.1518845451; _gid=GA1.1.1813137235.1518845451
Host:localhost
Origin:http://localhost
Referer:http://localhost/videos/beyond/vimeo-upload-master/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

**Response**
Method not allowed!
The PUT method is not allowed for the requested URL.

If you think this is a server error, please contact the webmaster.

Error 405
localhost
Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/5.6.30 mod_perl/2.0.8-dev Perl/v5.16.3

**Comment by erunion** [comment]
Hey @nikunjprajapati77, I've redacted your API access token above, and deleted it from our database. 

API access tokens give you complete access to one's Vimeo account, so treat them safely.

Please contact our support team at https://vimeo.com/help/contact and someone can help you there.
