### ISSUE TITLE
comma separated JSON filters don't work anymore

### ISSUE THREAD

**Issue by vladfulgeanu** [vimeo/vimeo.js#64]
After updating to the 2.0.0 version (so the 3.4 API version) using the following request:
```
vimeoApi.request(`/videos/${vimeoId}?fields=status,files`, (error, body, status_code, headers) => {
...
});
```
will **only** give the _status_ and **not** the _files_ field.

**Comment by vladfulgeanu** [comment]
This still gives only _status_, without _files_:
```
vimeoApi.request({
    method: 'GET',
    path: `/videos/${vimeoId}`,
    query: {
        fields: 'status,files'
    }
}, (error, body, status_code, headers) => {
...
});
```

**Comment by vladfulgeanu** [comment]
It seems that this is a problem of the Vimeo API's from version 3.3 onwards.

**Comment by erunion** [comment]
@vladfulgeanu I'll have someone look into this first thing tomorrow morning.

**Comment by Sventour** [comment]
Hi @vladfulgeanu, use version `3.2` for this request and be the owner of the video to obtain access to the `files` key.

**Comment by vladfulgeanu** [comment]
@Sventour Yes, I did that. But I still think the documentation should be updated. Will API's 3.3+ support `files` key anymore?

**Comment by erunion** [comment]
@vladfulgeanu It will. This is a bug that we're pushing out a fix for soon to restore this data to v3.4.

**Comment by erunion** [comment]
@vladfulgeanu We just deployed a fix to restore the `files` data for v3.4 requests. Can you verify you're seeing it again?

**Comment by vladfulgeanu** [comment]
@erunion Yes, it works now, thanks!
One additional small question regarding the new vimeo.upload() method:
- is there a way to get the response headers in the `completeCallback` function, given that it only has the new `uri` as parameter?

**Comment by erunion** [comment]
Awesome, glad it's working again.

Right now it's not possible to get response headers in `completeCallback`, but it's certainly something that can be added. Note, however, that the tus library that we're using unfortunately doesn't support returning headers from your piecemeal upload(s) in that callback, so any headers that you would be able to get back would be from the upload attempt and not the actual upload. 

Though I assume you're looking for information on rate limits? Those would be present in the upload attempt anyway, and not the upload.

**Comment by vladfulgeanu** [comment]
@erunion Has anything been changed? It seems that I don't get the `files` key anymore?

**Comment by erunion** [comment]
No, nothing has changed and I'm still seeing the `files` key for my videos. Can you send your access token to our support team at https://vimeo.com/help/contact so we can figure out what's going on?

The difference between an upload attempt and actual upload is that when we make an upload, we first create an "attempt". This creates the initial video in our database, and we then send back information for the actual upload to happen. See https://developer.vimeo.com/api/upload/videos#resumable-guide for more information.

**Comment by vladfulgeanu** [comment]
I was asking in regards to the vimeo.js library, can I get access to the response headers of the initial upload attempt?

**Comment by erunion** [comment]
Right now you cannot, but the library can be modified to support that.

**Comment by vladfulgeanu** [comment]
Right now just using the default vimeo.js library (v2.0.0), so not explicitly setting to use the API v3.2, will result in a missing `files` key in the response, it's weird because it worked for a little while a few hours ago.

I've sent the additional details to the support team.

**Comment by erunion** [comment]
Ok cool, they'll help you figure out what's going on.
