### ISSUE TITLE
Failed because: Unable to initiate an upload. [Error: {"error":"The app is not allowed to perform that action."}]

### ISSUE THREAD

**Issue by stefanspatialmedia** [vimeo/vimeo.js#67]
Hello.

I am doing the following code:

`'use strict';

const Vimeo = require('vimeo').Vimeo;
const credentials = require('./credentials.js');

const client = new Vimeo(credentials.client_identifier, credentials.client_secrets, credentials.access_token);

console.log(client);
client.upload(
    'sample.mp4',
    function (uri) {
        console.log('File upload completed. Your Vimeo URI is:', uri)
    },
    function (bytesUploaded, bytesTotal) {
        var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2)
        console.log(bytesUploaded, bytesTotal, percentage + '%')
    },
    function (error) {
        console.log('Failed because: ' + error)
    }
)
`
And it's giving me the above error. Console.log(client) shows the correct credentials. I've tried multiple access tokens with various levels of access. What could be causing this?

Any help appreciated!

**Comment by tommypenner** [comment]
To upload, devs must request upload access for their applications. If you haven't done this yet for your app, go to https://developer.vimeo.com/apps, select your app, click on "Request upload access", and follow the flow there. 

If your app does not have upload access, or has been denied access, upload metadata like your quota are not returned, and upload requests like what you reference will return an error.

If you have any questions about upload access for your application, contact Vimeo direct here (and reference this GitHub issue): https://vimeo.com/help/contact

**Comment by stefanspatialmedia** [comment]
I see, thanks for the quick reply. I've requested access.
Perhaps this can get a more descriptive error message? Currently the code will fail without printing one:

TypeError: Cannot read property 'space' of undefined
    at /home/stefan/Work/code/vimeo-service/node_modules/vimeo/lib/vimeo.js:445:49
    at IncomingMessage.<anonymous> (/home/stefan/Work/code/vimeo-service/node_modules/vimeo/lib/vimeo.js:177:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Thanks again!

**Comment by erunion** [comment]
@stefanspatialmedia Good idea.
