### ISSUE TITLE
TypeError: Cannot read property 'space' of undefined

### ISSUE THREAD

**Issue by mohammadbhuyan** [vimeo/vimeo.js#68]
I created an APP to upload video using Javascript SDK.
I **did not** request for upload acecess
I generated access token ticking all options.

Then I proceeded to use the SDK to call upload, a TypeError is raised.

```
node_modules/vimeo/lib/vimeo.js:177
        callback(null, body, res.statusCode, res.headers)
        ^
TypeError: Cannot read property 'space' of undefined
    at node_modules/vimeo/lib/vimeo.js:445:49
    at IncomingMessage.<anonymous> (node_modules/vimeo/lib/vimeo.js:177:9)
```

I confirmed that line 445 in vimeo.js:

```
this.request('/me?fields=upload_quota.space.free', function (err, response, status) {
    if (err) {
      return errorCallback('Unable to pull the users upload quota. [' + err + ']')
   } else if (fileSize > response.upload_quota.space.free) { 
      return errorCallback('User does not have any more free space to upload this video.')
    }
```
***the 'response' object is empty (status=200) hence 'upload_quota' is undefined,***
Hence: Cannot read property 'space' of undefined

While I am waiting for my upload access to get approved, I am guessing free space check response is not playing sane until the upload permission is approved.

In any case, it should be proper error handling than a TypeError?

Regards,

Mohammad

**Comment by erunion** [comment]
We aren't doing upload quota checks during uploads, so this is no longer valid.
