### ISSUE TITLE
GET /videos endpoint does not work for links

### ISSUE THREAD

**Issue by gurupras** [vimeo/vimeo.js#71]
I'm trying to get the video metadata given a vimeo video URL, and found from [this StackOverflow answer ](https://stackoverflow.com/a/34027757/1761555) that I should use the `https://api.vimeo.com/videos` endpoint with the `links` query parameter.

When I try to fire this query via this library with:
```
const queryStr = undefined
const links = 'https://vimeo.com/35055590'

client.request({
  method: 'GET',
  path: '/videos',
  query: {
    query: undefined,
    links: links,
    sort: 'relevant',
    per_page: 50,
    page: 1,
    fields: 'name,pictures.sizes,user.name,link'
  }
}, (err, body, code, headers) => {
  if (err) {
    console.error(err)
  }
})
```

I get an error reporting: 
```
Error: {"error":"Something strange occurred. Please try again.","link":null,"developer_message":"The query param provided is not supported for the request.","error_code":2101}
    at IncomingMessage.<anonymous> (/home/guru/workspace/videoshare-development/node_modules/vimeo/lib/vimeo.js:164:19)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by tommypenner** [comment]
You're using the `/videos` endpoint as opposed to the `/videos/[video_id]` endpoint. Use that /videos/[video_id] endpoint to get a video's metadata. Documentation here: https://developer.vimeo.com/api/reference/videos#GET/videos/{video_id}

**Comment by gurupras** [comment]
The [StackOverflow answer](https://stackoverflow.com/a/34027757/1761555) which appears to be from Vimeo states:
>  you provide a comma separated list of your Vimeo urls via the "links" parameter to the search endpoint (https://developer.vimeo.com/api/endpoints/videos#GET/videos) we will return those videos as API responses.
>e.g.
>```GET https://api.vimeo.com/videos?links=https://vimeo.com/74648232,https://vimeo.com/232323497```

The whole point of this query was to determine the video ID yet your comment suggests that I already need the video ID.

**Comment by gurupras** [comment]
I guess I'll just continue using the `https://vimeo.com/api/oembed.json`. I wish you'd considered what I was describing before instantly closing the issue.

**Comment by erunion** [comment]
@gurupras It looks like our `links` parameter is actually broken there. I just filed a ticket and we'll patch it up as soon as we can.

**Comment by erunion** [comment]
Or if you can, until `links` is fixed, you could alternatively use the `uris` parameter. It does the same thing, your payload will just need to look like:

> GET https://api.vimeo.com/videos?uris=/videos/74648232,/videos/232323497

**Comment by gurupras** [comment]
Thanks for the update. My real problem was lack of a standardized way of parsing a Vimeo URL to obtain something that I _then_ use to get video metadata, but this looks very promising. It looks like I just need to strip out the `host` part of the URL which should be trivial.

**Comment by erunion** [comment]
Hey @gurupras, I looked into this this morning and there isn't a bug here. What's going on is that we don't allow sorting on batch requests to `/videos`. 

Remove `sort: 'relevant',` from your request and it'll succeed.

**Comment by gurupras** [comment]
Ah okay great. I'll update my requests to remove `sort` when trying to use `links`. Thanks a lot for looking into this!
