### ISSUE TITLE
Q: Generate Video Thumbnails in NodeJS

### ISSUE THREAD

**Issue by DQvsRA** [vimeo/vimeo.js#72]
Hello, Vimeo Team

Is there any way how I can generate thumbnails for video on vimeo in NodeJS or make a request for that?

Thanks,
Vladimir

**Comment by tommypenner** [comment]
Take a look at the thumbnail upload docs here: https://developer.vimeo.com/api/upload/pictures

If you want to create a thumbnail from a specified time/frame in the video, use the endpoint documented here: https://developer.vimeo.com/api/reference/videos#POST/videos/{video_id}/pictures

**Comment by DQvsRA** [comment]
I did not try to create, but getting the thumbs was possible, @tommypenner thank you!
And what about GIF animation, is it possible to make a gif preview?

**Comment by erunion** [comment]
@DQvsRA It is unfortunately not possible to make gif previews.
