### ISSUE TITLE
This dependency was not found:  * fs in ./node_modules/vimeo/lib/vimeo.js

### ISSUE THREAD

**Issue by JosephCarrington** [vimeo/vimeo.js#76]
When using next.js

**Comment by aecorredor** [comment]
Same thing happening to me.

**Comment by aecorredor** [comment]
This is the problem: https://github.com/zeit/next.js/issues/2734

**Comment by aecorredor** [comment]
@JosephCarrington I checked the code and `fs` is only used to upload videos. If you follow the link to the issue I included on the previous comment there's a way to exclude `fs` from being compiled by webpack. I'm about to try that.

**Comment by aecorredor** [comment]
@JosephCarrington ok so that works, try adding this to your `next.config.js`:

`module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.node = {
        fs: 'empty',
      };
    }

    return config;
  },
};`

That would include `fs` on the client but exclude it from the `server`.

**Comment by erunion** [comment]
Thanks for looking into that @aecorredor.

**Comment by AbingPj** [comment]
Any idea how to solve it on nuxt.js

**Comment by arbexmb** [comment]
> config.node = {
>         fs: 'empty',
>       };

I am wondering the same thing. Did you manage to solve it on nuxt @AbingPj ?

**Comment by arbexmb** [comment]
> Any idea how to solve it on nuxt.js

I am wondering the same thing. Did you manage to solve it on nuxt.js @AbingPj ?
