### ISSUE TITLE
Failed to load resource: Request header field User-Agent is not allowed by Access-Control-Allow-Headers.

### ISSUE THREAD

**Issue by aecorredor** [vimeo/vimeo.js#78]
I cannot get videos from https://api.vimeo.com/users/${user}/videos when using my front-end app in mobile browsers. Has anyone else encountered this? Am I missing something? My app works fine in desktop browsers.

**Comment by aecorredor** [comment]
I just found this in the docs: User Agents
Make sure to set a custom User Agent for your app. We will be much less likely to block access if we see a custom User Agent! We block certain generic User Agents now, and may block others in the future.

**Comment by aecorredor** [comment]
I'm setting the user agent in my headers to Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1 but I am still getting blocked in mobile browsers.

**Comment by erunion** [comment]
That's really weird. We're looking into it.

**Comment by aecorredor** [comment]
@erunion I switched from using the Vimeo JS SDK to just making the request directly with axios and it's working now. Also, I started using a client/secret ID from a PRO account now, I don't know if that has anything to do with it. I don't think so because before I was still getting the videos back in desktop browsers even with non-PRO credentials.

**Comment by erunion** [comment]
Account type shouldn't have had any affect on this, but that's good to know regardless.

We'll hopefully have an update later today when we have more info on why this wasn't working to begin with.

**Comment by erunion** [comment]
We'll be adding `User-Agent` to our CORS headers. Should be done late this/early next week.

**Comment by erunion** [comment]
Looks like this fix went out late last week. Please lus know if you are still having problems with it.
