### ISSUE TITLE
Question: what is the recommended way to add a custom user agent?

### ISSUE THREAD

**Issue by aecorredor** [vimeo/vimeo.js#79]
As per the vimeo API guidelines, it is recommended to add a custom user agent to my app. I am wondering what’s the correct way you guys expect me to do this? Because I am still getting blocked on mobile clients.

**Comment by erunion** [comment]
On the `request` method, you can supply an object of headers you want to set for the request, which'll override some defaults we have configured in the SDK:

```js
client.request({
  path: '/me',
  headers: {
    'User-Agent': '<your custom user agent>'
  }
}, callback)
```

See the [request method docs](https://github.com/vimeo/vimeo.js#make-requests) for more info.

**Comment by aecorredor** [comment]
@erunion That's what I figured, and it's what I tried, but for some reason it wasn't working in mobile browsers because my request was still getting blocked. Thanks for the quick response though.
