### ISSUE TITLE
Follow Userlist 

### ISSUE THREAD

**Issue by hoemon** [vimeo/vimeo.js#87]
Could not seem to make it work
https://developer.vimeo.com/api/playground/me/following

With or without the API, I can't seem to follow a "list of users"

/me/following/[userid] works via patch, but I have to -somehow- provide a list of users if I want to follow a list of users (using POST method) - I can't seem to figure this one out. 

Any help is appreciated.

**Comment by tommypenner** [comment]
Are you having the same trouble when using a REST client like Postman or command-line curl?

When using the Playground, are you logged into a Vimeo account or logged out?

**Comment by hoemon** [comment]
Logged in.
Everything else works (directly on the playground).

Actually I'm looking for a solution to follow multiple people (just like the api suggests) via a list/array of usersids using this library.

I was unable to find any examples for this. Tried passing a "users" array to query, didn't work.

**Comment by hoemon** [comment]
`Error: {"error":"Something strange occurred. Please try again.","link":null,"developer_message":"The body of this HTTP request is not formatted properly. Please check the content-type header and raw body.","error_code":2205}`

**Comment by hoemon** [comment]
Any help is apprediated

**Comment by hoemon** [comment]
Hm, I see - how can I test this on the js library using nodejs?
I have no clue on how to test this using Postman or anything similar (no idea how to login, etc)

**Comment by hoemon** [comment]
Tried sending the array as json using postman, it works! However I couldn't figure out howe to do this using the api.
Here is what I tried

`
let userArr = [
	{uri:"/users/11111111"},
	{uri:"/users/22222222"},
	{uri:"/users/33333333"}
];
followUserArray(userArr);

function followUserArray(arr) {
	client.request({
		method: "POST",
		path: "/me/following/",
		query: {
			users: arr,
		}

	}, function(error, body, status_code, headers) {
		console.log("status code", status_code)
		if (error) console.log(error);
		console.log(headers)
		console.log(body)
	});
}
`
And I get this as a response

`
{"error":"Something strange occurred. Please try again.","link":null,"developer_message":"The body of this HTTP request is not formatted properly. Please check the content-type header and raw body.","error_code":2205}
`

**Comment by hoemon** [comment]
Just tried converting the json/object to a string (as I believe the nodejs api acceps only string) via
`encodeURIComponent(JSON.stringify(arr)`
but I get the same error response.

**Comment by tommypenner** [comment]
Instead of `query`, put the array of objects into `params`, take a look at the example here: https://github.com/vimeo/vimeo.js/blob/master/example/upload.js#L64-L71

```
		method: "POST",
		path: "/me/following/",
		params: [
	{"uri":"/users/11111111"},
	{"uri":"/users/22222222"},
	{"uri":"/users/33333333"}
]
```

**Comment by hoemon** [comment]
Maybe it was supposed to be as follows

```
params: {
    users: userArr
}
```

However I'm still getting the same response from the api.
