### ISSUE TITLE
upload video while recording?

### ISSUE THREAD

**Issue by yasirrose** [vimeo/vimeo.js#97]
Can i upload the video without providing the size of the file through resume able approach?

I want to upload my video while recording on vimeo. In this case, after every 2 sec, i will get binary data from player and send it to vimeo. But for this case, the size of video file will not be provided.

**Comment by erunion** [comment]
Unfortunately, no. 

You can do this with our livestreaming APIs by streaming to us as your video is recording and when the stream is over we'll automatically create an archive for you. Unfortunately those APIs are currently private but if you'd like access please contact our community team at https://vimeo.com/help/contact and they'll forward you to someone who can field your request.
