### ISSUE TITLE
API call not returning correct album order

### ISSUE THREAD

**Issue by Lahori-Jawan** [vimeo/vimeo.js#98]
Hi. I am calling the `https://api.vimeo.com/users/<user_id>/albums/<album_id>/videos` to get videos from a specific album and have set order by drag-n-drop but the json result does not reflect that. is it supposed to be like that or ?

**Comment by mandeldl** [comment]
Hi @Lahori-Jawan can you try passing the query param for manual sort:
`https://api.vimeo.com/users/<user_id>/albums/<album_id>/videos?sort=manual`
https://developer.vimeo.com/api/reference/albums#get_album_videos

**Comment by Lahori-Jawan** [comment]
Thank you @mandeldl it works now. @tommypenner your solution works too. Thanks. 
BTW I think this should be the default behavior.
